## ----------------------------------------------------------------------------
## Script     : makefile.sources
## ----------------------------------------------------------------------------
## Author     : Johann Faerber
## Company    : University of Applied Sciences Augsburg
## ----------------------------------------------------------------------------
## Description: provide all the VHDL source files in the variable SYN_SOURCE_FILES
##              Attention !!!
##              -------------
##              Do not forget a new line after the final source file !
## ----------------------------------------------------------------------------

SYN_SOURCE_FILES = \
../../src/pattern_generator.vhd \
../../src/cntup_addr.vhd \
../../src/pattern_generator_fsm.vhd \
../../src/sp_ssram_rtl.vhd \
../../src/cntdnmodm_rtl.vhd \

# do not delete this line
# -----------------------------------------------------------------------------
